### PR TITLE
Add Average Cow Health Service and test

### LINKED ISSUE #20: FEATURE: Add Average Cow Health Service and Test
## Overview

In this issue, Average Cow Health Service need to be implemented to implement #12 

## Acceptance

- [ ] There is a file called `AverageCowHealthServiceTest.java`
- [ ] There is a file called `AverageCowHealthService.java`
- [ ] Passed releated tests

### PR DESCRIPTION
**Pull request by mier2**
## Overview
In this pr, I implemented Average Cow Health Service and test

## Tests

- [x] `mvn test`
- [x] `mvn test jacoco:report`
- [x] `mvn test org.pitest:pitest-maven:mutationCoverage`

Closes #20

### CODE REVIEW

**Review by clin947 — DISMISSED** [review]
LGTM!

**Review by clin947 — DISMISSED** [review]
Tested locally and passed. LGTM!

**Review by ryan-he-8 — DISMISSED** [review]
lgtm

**Review by ryan-he-8 — DISMISSED** [review]
lgtm

**Review by clin947 — DISMISSED** [review]
lgtm

**Review by ryan-he-8 — APPROVED** [review]
lgtm

**Review by jingpeng7527 — APPROVED** [review]
lgtm!

**Pull request merged**
